fix #54 updateShouldNotify
rrousselGit/state_notifier pull request #57
Opened 2021-12-17 00:28 UTC by maxzod

to be able to use `==` or `identical`

2021-12-19 21:31 UTC, ebelevics requested changes
This proposal is weird as it is exact opposite of object reference comparison. Meaning _state = OldInstanceOfState() and _value = NewInstanceOfState() won't notify which is not natural.

My proposal is giving additional option to users notifying changes without object comparison, for example:
```dart
  @protected
  set notify(T value) {
    assert(_debugIsMounted(), '');
    _state = value;
    _controller?.add(value);

   ...
  }
```
because streams doesn't care is value any different, it just cares if new event is added.

And user then can call `notify = state..someDeepValueChangeMethod()` to notify listeners. 

You could then also add another additional method `notifyListeners() => notify = state;` in StateNotifier as option, to eliminate need for changeNotifier all together. Please correct me if I'm wrong. Naming of course is arbitrary.

2021-12-19 22:05 UTC, rrousselGit commented on packages/state_notifier/lib/state_notifier.dart
> +    if (!updateShouldNotify(_state, value)) {
Could you write tests for this? :pray:

2021-12-19 22:11 UTC, maxzod commented on packages/state_notifier/lib/state_notifier.dart
> +    if (!updateShouldNotify(_state, value)) {
sure

2021-12-29 21:19 UTC, rrousselGit commented on packages/state_notifier/README.md
> +### can i override this behavior ?
```suggestion
### How to change this behavior?
```

2021-12-29 21:21 UTC, rrousselGit commented on packages/state_notifier/README.md
> +yes by overriding `updateShouldNotify(T old,T current)`
```suggestion
You can override the method `updateShouldNotify(T old,T current)` of a `StateNotifier` to change the default behaviour, such as for:
- using `==` instead of `identical` to filter updates, for deep state comparison
- always return `true` to revert to older behaviors of `StateNotifier`
```

2021-12-29 21:23 UTC, rrousselGit commented on packages/state_notifier/README.md
> +    return current != old;
```suggestion
  bool updateShouldNotify(User old, User current) {
    /// only update the User content changes, even if using a different instance
    return old.name != current.name && old.age != current.age;
```

2021-12-29 21:23 UTC, rrousselGit commented on packages/state_notifier/lib/state_notifier.dart
> +  /// decide should notify listeners or not before each update
```suggestion
  /// Whether to notify listeners or not when [state] changes
```

2021-12-29 21:26 UTC, rrousselGit commented on packages/state_notifier/test/update_shoud_notifiy_test.dart
> +    );
I don't think that's the expected behavior.
I'd expect the state to correctly decrement, but listeners to not be called.

Could you update the test/code to verify/do that instead? thanks :pray:

2021-12-29 21:28 UTC, maxzod commented on packages/state_notifier/test/update_shoud_notifiy_test.dart
> +    );
ok

2022-01-15 14:05 UTC, rrousselGit commented
LGTM thanks!

2022-01-15 14:26 UTC, merged

2022-01-15 14:28 UTC, rrousselGit commented
Released in version 0.7.2