Add StateNotifierListener and MultiStateNotifierListener
rrousselGit/state_notifier pull request #73
Opened 2023-04-15 16:59 UTC by robsonsilv4

This PR closes #64 by adding `StateNotifierListener` and `MultiStateNotifierListener`*, based on [BlocListener ](https://pub.dev/documentation/flutter_bloc/latest/flutter_bloc/BlocListener-class.html) and [MultiBlocListener](https://pub.dev/documentation/flutter_bloc/latest/flutter_bloc/MultiBlocListener-class.html) from [flutter_bloc](https://pub.dev/packages/flutter_bloc) (that uses [Provider](https://pub.dev/packages/provider)).

*`MultiStateNotifierListener ` was also added, because solves the problem of nested `StateNotifierListener`.

Notes:
- I used names based on current implementations for variables and examples, like `Controller`, `Value` etc (`Notifier` in tests).
- I'm added documentation for both widgets and update changelog with new the widgets.

2023-04-15 17:02 UTC, robsonsilv4 commented
Thanks to @felangel and all [flutter_bloc contributors](https://github.com/felangel/bloc/graphs/contributors) for the base code.

2023-04-15 17:16 UTC, rrousselGit commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +abstract class StateNotifierListenerBase<
What's the use of. this class?

2023-04-15 17:16 UTC, rrousselGit commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +    _controller = widget.value ?? context.read<Controller>();
This is dependent on package:provider. Wasn't the point to be independent from it?

2023-04-15 18:34 UTC, robsonsilv4 commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +abstract class StateNotifierListenerBase<
It just a base class (for abstraction), but it's not needed in the `flutter_state_notifier`, like in `flutter_bloc`. I'll remove.

2023-04-15 18:43 UTC, robsonsilv4 commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +    _controller = widget.value ?? context.read<Controller>();
Good observation! I forget that `flutter_state_notifier` can be used together with `Provider`, instead of replace it (like in the `flutter_bloc`). I'll do refactor to work similar to `StateNotifierProvider`.

2023-04-15 19:07 UTC, robsonsilv4 commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +    _controller = widget.value ?? context.read<Controller>();
Hi @rrousselGit, I'm working on this, but i have a question: can I continue extending `SingleChildWidget`? I can use `StatefulWidget` (already tested), but without `SingleChildWidget`, I can't implements `MultiStateNotifierListener`. Do you have any tip?

2023-04-19 08:39 UTC, rrousselGit commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +    _controller = widget.value ?? context.read<Controller>();
A MultiStateNotifierListener is overkill. We don't really need this. The Listener widget is going to be pretty rarely used already anyway

2023-04-25 13:33 UTC, robsonsilv4 commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +    _controller = widget.value ?? context.read<Controller>();
Got your point and make sense. In most cases, I use only one `Listener` and sometimes two, but rarely three or more.
I'll remove the `MultiStateNotifierListener` and update the implementation and docs.

2023-05-07 23:53 UTC, robsonsilv4 commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +    _controller = widget.value ?? context.read<Controller>();
Hi @rrousselGit , I've removed the dependency of the `package:provider`, updated API docs and updated README docs with `StateNotifierListener` usage. Also, I've removed the `MultiStateNotifierListener` and updated tests.

Waiting for feedback or approve.

2023-05-07 23:53 UTC, robsonsilv4 commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +abstract class StateNotifierListenerBase<
Already removed in previous commits.

2023-05-10 08:40 UTC, rrousselGit commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +    _previousState = _controller.state;
The code should be refactored to not trigger this warning

2023-05-10 08:40 UTC, rrousselGit commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +class StateNotifierListener<Controller extends StateNotifier<Value>, Value>
Name "Controller" `NotifierT` instead

2023-05-10 08:41 UTC, rrousselGit commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +    _subscription = _controller.stream.listen((state) {
Don't use `.stream`

Use `notifier.addListener`

2023-05-10 08:42 UTC, rrousselGit commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +    Value previous, Value current);
```suggestion
    Value previous, Value current,);
```

2023-05-10 08:43 UTC, rrousselGit commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +typedef StateNotifierWidgetListener<Value> = void Function(
The listener should receive both the previous and current state.

Both are available when using StateNotifier.addListener

2023-05-10 08:44 UTC, rrousselGit commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +  late Value _previousState;
There should be no need for this property

2023-05-10 08:44 UTC, rrousselGit commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +  late Value _previousState;
In fact I doubt we even need the controller, all things considered 😛

2023-05-10 08:46 UTC, rrousselGit commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +    properties.add(DiagnosticsProperty<Controller>('state', _controller));
The name "state" doesn't really make sense when considering that it's a StateNotifier.

Also, the controller isn't owned by the `State` class ultimately, but by the `StatefulWidget` bit.
The debugFillProperties probably should be moved there instead.

2023-06-06 10:25 UTC, rrousselGit requested changes
Hello! Do you still plan to work on this? There are a few unresolved comments :)

2023-08-16 08:36 UTC, rrousselGit commented
:wave:

Since this seems to be stale. I'll close this. Feel free to reopen a PR if you wish to continue working on it :)

2023-08-16 08:36 UTC, closed without merging

2023-12-26 12:41 UTC, robsonsilv4 commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +typedef StateNotifierListenerCondition<Value> = bool Function(
Yep, removed. It was previously added for use in StateNotifierListener and StateNotifierMultiListener.

2023-12-26 12:44 UTC, robsonsilv4 commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +    _subscription = _controller.stream.listen((state) {
Good rule. I did not remember that `addListener` returns a callback to remove the subscription.

2023-12-26 12:46 UTC, robsonsilv4 commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +class StateNotifierListener<Controller extends StateNotifier<Value>, Value>
Renamed. I was following the older generics' convention, but these new names are better :)

2023-12-26 12:47 UTC, robsonsilv4 commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +    BuildContext context, Value state);
Added :)

2023-12-26 12:47 UTC, robsonsilv4 commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +    Value previous, Value current);
Added :)

2023-12-26 14:33 UTC, robsonsilv4 commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +typedef StateNotifierWidgetListener<Value> = void Function(
Can you give me a hint to achieve your suggestion?

I tried to access the previous and current state value, but the `.state` and `state` from addListener callback logs the same value:

```dart
void main() {
  final notifier = CounterNotifier();
  notifier.addListener((state) {
    log('Previous state: ${notifier.state}');
    log('Current state: $state');
  });
  notifier
    ..increment()
    ..increment();
}
```

2023-12-26 14:56 UTC, robsonsilv4 commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +    properties.add(DiagnosticsProperty<Controller>('state', _controller));
I moved to the StatefulWidget, but `debugFillProperties` already has `super.debugFillProperties(properties)` that includes stateNotifier. So I completely removed the `debugFillProperties` override.

2023-12-26 15:21 UTC, robsonsilv4 commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +  late Value _previousState;
The `_controller` is used to control `didUpdateWidget`, `didUpdateWidget` and `subscription` in these lifecycles.
So if I remove the `_controller`, these lifecycles will back to default behavior.

Do you have some suggestions?

2023-12-26 17:11 UTC, robsonsilv4 commented on packages/flutter_state_notifier/lib/flutter_state_notifier.dart
> +    _previousState = _controller.state;
This warning already ignored in other implementations, like in StateNotifierProvider

Do you have a suggestion for the refactor?

I can think of two possibilities:
- Using `debugState`, but it not work on release mode
- Or keeping a local variable for current state, like `previousState`

2023-12-26 17:17 UTC, robsonsilv4 commented
Hi @rrousselGit , thanks for the suggestions, and sorry for the delay. I was a little busy at the time
Can you re-open the PR? I answered and update the implantation based on the comments
Let me know if you want to modify something else :)